name: Test Package CI

on:
  push:
    branches: '!main'
  pull_request:
    branches:
    - main
    - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '11'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@9.4
      with:
        # Install just one or all simultaneously
        # The value must indicate a particular version of the tool, or use 'latest'
        # to always provision the latest version
        cli: 1.11.1.1155              # Clojure CLI based on tools.deps

    - name: Cache clojure dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.deps.clj
        # List all files containing dependencies:
        key: cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: cljdeps-

    - name: Generate Package
      run: clojure -T:generator jar

    - name: Set TAG env variable
      run: echo "TAG=$(grep :version release.edn | awk -F" " '{print $2}' | tr -d "\"")" >> $GITHUB_ENV

    - name: Test Package
      run: cp -r test target/ && cd target && clojure -Sforce -Sverbose -Sdeps '
                   {:deps {com.cicadabank/bips {:local/root "bips-${{env.TAG}}.jar"},
                           clj-async-test/clj-async-test {:mvn/version "0.0.5"},
                           io.github.cognitect-labs/test-runner {:git/tag "v0.5.0"
                                                                 :git/sha "b3fd0d2"}},
                    :paths ["test/"]}' -m cognitect.test-runner
